# Generated by Django 5.2.3 on 2025-06-17 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Carts', '0002_cartitem_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='variation',
            new_name='variations',
        ),
    ]
