# Generated by Django 5.2.3 on 2025-06-20 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_remove_orderproduct_payment_remove_order_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
    ]
