# Generated by Django 5.2.3 on 2025-06-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_remove_orderproduct_color_remove_orderproduct_size'),
        ('Store', '0002_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='variation',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='variations',
            field=models.ManyToManyField(blank=True, to='Store.variation'),
        ),
    ]
